### ISSUE TITLE
Groups not accessible from home page

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/galene_ynh#111]
Groups not accessible from home page ->  `https://visio.domain.tld/undefined`
but accesible with direct link `https://visio.domain.tld/group/my_group`
https://forum.yunohost.org/t/latest-galene-update/24203

**Comment by jech** [comment]
Also reported upstream: https://github.com/jech/galene/issues/157.  I've been unable to reproduce the issue.
