### ISSUE TITLE
Yunohost Galene Update Overwrites Files

### ISSUE THREAD

**Issue by ralphshinevar** [YunoHost-Apps/galene_ynh#117]
--- 
Everytime there is an update to Galene in Yunohost, these two files get overwritten:

/home/[yunohost.app/galene/groups/public.json](http://yunohost.app/galene/groups/public.json)
/var/www/galene/live/data/config.json

I backed up the files before the update.  Also the permissions get changed from 0644 to 0600.

*A clear and concise description of what the bug is.*

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.1.19 (stable).
- I have access to my server: *Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No

### Steps to reproduce

    ```
Updated Galene from Webadmin
    ```

### Expected behavior

Galene updated with front page groups links to lead to group logins.  

### Logs ###

May 15 10:59:01 systemd[1]: Stopping Galène: videoconferencing server...
May 15 10:59:01 systemd[1]: galene.service: Succeeded.
May 15 10:59:01 systemd[1]: Stopped Galène: videoconferencing server.
May 15 10:59:01 systemd[1]: galene.service: Consumed 35min 16.311s CPU time.
May 15 10:59:39 systemd[1]: Started Galène: videoconferencing server.
May 15 10:59:39 galene[990628]: 2023/05/15 10:59:39 /var/www/galene/live/data/config.json: invalid character '}' looking for beginning of value
May 15 10:59:39 galene[990628]: 2023/05/15 10:59:39 Starting built-in TURN server on 23.84.35.224:1195
May 15 10:59:39 galene[990628]: 2023/05/15 10:59:39 Group file /home/yunohost.app/galene/groups/public.json: invalid character '}' looking for beginning of value
May 15 10:59:39 galene[990628]: 2023/05/15 10:59:39 Unexpected extension for group file /home/yunohost.app/galene/groups/public.json.old
May 15 10:59:39 galene[990628]: 2023/05/15 10:59:39 Relay test successful in 20.806745ms, RTT = 388.063µs

**Comment by ericgaspar** [comment]
ok, sorry about that.
For the next iteration I will move `/var/www/galene/live/data/config.json` file to `/home/yunohost.app/galene/data/config.json` so we don't have to recreat it during upgrade and `/home/yunohost.app/galene/groups/public.json` will also be preserved.
