### ISSUE TITLE
Groups not accessible from home page

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/galene_ynh#143]
I have an issue with the default group JSON config  file. We use a hashed password:

https://github.com/YunoHost-Apps/galene_ynh/blob/fix-json/conf/groupname.json

here is the error output:

`Group file /home/yunohost.app/galene/groups/public.json: invalid character 't' after object key:value pair`

and the JSON file:

```
{
   "users":{
      "eric":{
         "permissions":"op",
         "password":"{"type":"pbkdf2","hash":"sha-256","key":"02b1d0dd5764a2b2cd3be64eaa32313700f49e3bef57b35718a46d43f3fbc41b","salt":"38d60fd09728b26d","iterations":4096}"
      },
      "description":"public group",
      "public":true,
      "allow-recording":true,
      "auto-subgroups":true
   }
}
```
@jech ping

**Comment by jech** [comment]
There's an extra pair of double quotes on line 5.

**Comment by ericgaspar** [comment]
Thanks for your reply.
After removing the double quotes I get this new JSON error: `/home/yunohost.app/galene/groups/public.json: json: cannot unmarshal string into Go struct field Description.users of type group.UserDescription`

**Comment by jech** [comment]
You need to close the `"users"` dictionary before you set the other fields.  Here's the corrected version:
```json
{
    "users":{
        "eric":{
            "permissions":"op",
            "password":{"type":"pbkdf2","hash":"sha-256","key":"02b1d0dd5764a2b2cd3be64eaa32313700f49e3bef57b35718a46d43f3fbc41b","salt":"38d60fd09728b26d","iterations":4096}
        }
    },
    "description":"public group",
    "public":true,
    "allow-recording":true,
    "auto-subgroups":true
}
```

**Comment by ericgaspar** [comment]
thank you for the help! it working now.
