### ISSUE TITLE
App still listed in wishlist

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/galene_ynh#18]
This app is still listed in wishlist : https://yunohost.org/#/apps_wishlist

Sorry to open an issue just for that, but I couldn't find where to edit that document… :sweat_smile:

**Comment by ericgaspar** [comment]
Thanks!
Removed from wishlist.

**Comment by lapineige** [comment]
How do you do it ? (next time maybe I'll be able to do it myself ^^)

**Comment by ericgaspar** [comment]
The repo is here : https://github.com/YunoHost/doc/blob/master/apps_wishlist.md
