### ISSUE TITLE
coturn cron job fucks up the ACL in /etc/ entirely

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/galene_ynh#23]
c.f. https://forum.yunohost.org/t/ssh-connection-reset/14728 and  https://github.com/YunoHost-Apps/galene_ynh/blob/testing/sources/Coturn_config_rotate.sh#L28 : `$app` is not defined, then the `setfacl` applies to the entirety of /etc/ ...

**Comment by alexAubin** [comment]
I guess we just need to `s/$app/__APP__` ?

**Comment by ericgaspar** [comment]
Thanks for reporting the issue, #22 should fix it
