### ISSUE TITLE
Error on domain change

### ISSUE THREAD

**Issue by stevenmache** [YunoHost-Apps/galene_ynh#32]
### Describe the bug
Error after changing the domain used by galene 

### Context
Rpi4b
Ynh 4.2.0
Ssh
No

### Steps to reproduce
1. Web admin > applications > galene
2. Change the generic domaine to my own
3. Save
4. Message saying the domain is successfully changed
5. User interface > galene 
6. Error message (page not found !) 

### Expected behavior
Having galene working on the new domain or having an error message and a rollback

### Logs
Sorry I reinstalled galene since. 
Original post on the forum [here](https://forum.yunohost.org/t/various-errors-on-domain-change/15163/11)  and [Here](https://forum.yunohost.org/t/error-on-restoring-and-reinstalling-galene/15172/8) .

**Comment by ericgaspar** [comment]
@stevenmache I did some tests on my server changing the domain name successfully: `visio.domain.ltd` -> `test.domain.ltd` -> `visio.domain.ltd`
Galène as to be installed in a subdomain or in a domain where there are no other applications installed. This excludes subdirectory  like: `domain.ltd/visio`

have you specified a domain name specifically used by Galène?

**Comment by stevenmache** [comment]
Hi Éric,

In my use case I changed from meet.domaine1.ynh.fr > meet.domaine2.fr

But, I don't know if during my attempt I did not enter a directory 🤔.

But the process went trough without warnings.

Cheers
Steven

________________________________
De : Éric Gaspar ***@***.***>
Envoyé : jeudi 1 avril 2021 à 10:22
À : YunoHost-Apps/galene_ynh
Cc : stevenmache; Mention
Objet : Re: [YunoHost-Apps/galene_ynh] Error on domain change (#32)


@stevenmache<https://github.com/stevenmache> I did some tests on my server changing the domain name successfully: visio.domain.ltd -> test.domain.ltd -> visio.domain.ltd
Galène as to be installed in a subdomain or in a domain where there are no other applications installed. This excludes subdirectory like: domain.ltd/visio

have you specified a domain name specifically used by Galène?

**Comment by stevenmache** [comment]
Yes it was specific to Galene
________________________________

**Comment by ericgaspar** [comment]
Is this still an issue after the #41 upgrade ?

**Comment by ericgaspar** [comment]
This issue seems to be a bug from the core : https://github.com/YunoHost/issues/issues/1798
