### ISSUE TITLE
Does port 8443 need to be opened?

### ISSUE THREAD

**Issue by h3ndrik** [YunoHost-Apps/galene_ynh#34]
My yunohost warns me that "Port 8443 is not reachable from outside". Is there any reason behind using both nginx as a reverse proxy and also opening the internal port directly to the internet?

If not: please consider removing that firewall directive. It also circumvents any authentication and security measures by nginx if the service is reachable via another port.

https://github.com/YunoHost-Apps/galene_ynh/blob/824143672c8aa5c64522a43636d4d369820a893b/scripts/install#L88

**Comment by ericgaspar** [comment]
Thanks for pointing it out. This should be corrected with #35
