### ISSUE TITLE
Cron in error when running Coturn_config_rotate.sh ($app missing)

### ISSUE THREAD

**Issue by stevenmache** [YunoHost-Apps/galene_ynh#36]
RPI4B @ ynh 4.2.0 with galene 0.3.2~ynh3

### Describe the bug

Hi Eric, I was playing around cron jobs and mail and stepped on this error:

Cronic detected failure or error output for the command:
bash -c /opt/yunohost/galene/Coturn_config_rotate.sh;

RESULT CODE: 0

ERROR OUTPUT:
grep: /etc//coturn.conf: No such file or directory
sed: can't read /etc//coturn.conf: No such file or directory
grep: /etc//coturn.conf: No such file or directory

STANDARD OUTPUT:

TRACE-ERROR OUTPUT:
+ ynh_validate_ip --family=4 --ip_address=109.8.95.73
+ local legacy_args=fi
+ args_array=([f]=family= [i]=ip_address=)
+ local -A args_array
+ local family
+ local ip_address
+ ynh_handle_getopts_args --family=4 --ip_address=109.8.95.73
+ set +o xtrace
+ '[' 4 == 4 ']'
+ python /dev/stdin
+ external_IP_line=external-ip=109.8.95.73/__IPV6__
+ '[' -n '' ']'
+ external_IP_line=external-ip=109.8.95.73
++ egrep '^external-ip=.*$' /etc//coturn.conf
grep: /etc//coturn.conf: No such file or directory
+ old_config_line=
+ ynh_replace_string '^external-ip=.*$' external-ip=109.8.95.73 /etc//coturn.conf
+ local legacy_args=mrf
+ args_array=([m]=match_string= [r]=replace_string= [f]=target_file=)
+ local -A args_array
+ local match_string
+ local replace_string
+ local target_file
+ ynh_handle_getopts_args '^external-ip=.*$' external-ip=109.8.95.73 /etc//coturn.conf
+ set +o xtrace
+ echo '! Helper used in legacy mode !'
+ set +x
+ local delimit=@
+ match_string='^external-ip=.*$'
+ replace_string=external-ip=109.8.95.73
+ sed --in-place 's@^external-ip=.*$@external-ip=109.8.95.73@g' /etc//coturn.conf
sed: can't read /etc//coturn.conf: No such file or directory
++ egrep '^external-ip=.*$' /etc//coturn.conf
grep: /etc//coturn.conf: No such file or directory
+ new_config_line=
+ setfacl -R -m user:turnserver:rX /etc/galene
+ '[' '' '!=' '' ']'
+ exit 0

### Describe the root cause

I look at the file /opt/yunohost/galene/Coturn_config_rotate.sh
and the path is expecting a variable $app, which on my config is not declared, resulting in : /etc//coturn.conf instead of /etc/galene/coturn.conf

 I don't know if it is the way to do in the packadge but I added app="galene" and it fixed it for me.

Cheers,
Steven

**Comment by ericgaspar** [comment]
Thanks Steven for pointing this out. It should be fixed with #37

**Comment by ericgaspar** [comment]
Fixed with #37. Closing
