### ISSUE TITLE
petit crash dans une conf

### ISSUE THREAD

**Issue by stevenmache** [YunoHost-Apps/galene_ynh#38]
Rpi4b@ynh 4.2.0, galene 0.3.2~ynh3 

Salut Éric, juste pour info, j'ai eut un petit crash avec galene. Je ne sais pas si cela est du a galene ou a l'intégration avec ynh ou mon navigateur. 
J'ai redémarré le service galene et ça remarche. 

Voici le log : https://paste.yunohost.org/luwezesali

Bonne journée
Steven

**Comment by ericgaspar** [comment]
As-tu ouvert les ports `49152:65535` comme décrit dans le README avec la commande `sudo yunohost firewall allow Both 49152:65535` ?

**Comment by stevenmache** [comment]
Ah, alors je crois que on les a retiré des regles avec Aleks car visiblement les regles xxxxx:xxxxx ont un effet inattendu depuis la 4.2.0 (ca faisait une erreur du genre unexpected ascii in < opération)
C'est dans un de mes posts que le forum.

Du coup si je te suit, ma conf a planté au changement de coturn, quelque chose comme ça ?

Merci
Steven

Apr 17, 2021 5:29:34 PM Éric Gaspar ***@***.***>:

**Comment by jech** [comment]
C'est réparé dans galene-0.3.3: https://github.com/jech/galene/commit/9533c208863cfefde2af5227219ead61db00d207

Désolé pour le bug.

**Comment by ericgaspar** [comment]
Should be fixed. Please open a new issue if necessary
