### ISSUE TITLE
Do I need a Yunohost account for each Galène user? 

### ISSUE THREAD

**Issue by rican13** [YunoHost-Apps/galene_ynh#42]
Hello,
I am not posting a bug but a question, because in my installation I have to use a known user of Yunohost to connect directly to a "group"!
Is this a mistake on my part?
Thank you in advance for your reply.
Ricardo

**Comment by lapineige** [comment]
Hello,

Did you install Galène privately ? (when it requested if it had to be accessible to any visitor,  even without an account, did you anwser "no" ?)
If so, you need a Yunohost account to access it, but any account is enough.

Galène users are not integrated with Yunohost user management system (Yunohost SSO (SingleSignOn) is based on LDAP (an SSO tool) witch Galène don't support yet). So the users defined in Yunohost have no influence on the ones defined in Galene configuration files. Except that you can restrict access to people logged in Yunohost (the SSO system will protect Galène from non-logged in visitors).

If you wish anyone, even without a Yunohost account (on your server I mean), you will have to add Galène app to the "visitors" permission group in Yunohost admin interface: https://yunohost.org/en/groups_and_permissions
I can tell you the details about this operation is you want, feel free to ask :slightly_smiling_face: 


Please note that you can allow anyone to access Galène home page (even non Yunohost user), but still prevent them to join a group that is not public (= listed in the home page) and/or that is public but password (or login+password) protected.

**Comment by rican13** [comment]
Thank you for your reply !
Indeed, at the time of installation, I had not understood the question on "the application must be accessible to any visitor or not", and in doubt I had answered "no", making it " private "!
I have just made the modification, that is to say:
on Yunohost, add the Galène application to the "visitors" authorization group in the application administration interface.
And indeed it works very well to directly access a "group", without being a user defined in Yunohost.
And of course in Galène, I only declared groups requiring a "user" and a "password"!

Can I ask you another question?
It concerns access to "statistics", ie to the "/ stats" directory!
Galene asks me for a username and password.
I use the one defined in the "/ opt / yunohost / galene / data / passwd" file but it doesn't work!

Thanks in advance for your help.
Ricardo

**Comment by lapineige** [comment]
> Indeed, at the time of installation, I had not understood the question on "the application must be accessible to any visitor or not",

That question is indeed unclear in many situations…

> Galene asks me for a username and password.

The ones defined during the installation (probably your YNH username  + the administration password), which should indeed be in `/opt/yunohost/galene/data/passwd`… what about your YNH user password ? Just in case 🤔

**Comment by rican13** [comment]
. Question concerning access to statistics:
I tried all the username and password saved on Yunohost and during installation and it doesn't work.
In the documentation of Galène, I saw that it was enough to define a couple "user: password" in the file "/opt/yunohost/galene/data/passwd" then to restart the service galene, but that does not not working !

**Comment by ericgaspar** [comment]
That is an issue...

**Comment by rican13** [comment]
Hello,
Thank you for your responsive help.
Good luck with resolving the issue.
Ricardo
