### ISSUE TITLE
Galene coturn server is not configured correctly: /relay-test fails

### ISSUE THREAD

**Issue by jakobkilian** [YunoHost-Apps/galene_ynh#43]
Hey there. A big thx for your great work on Yunohost and Galene at first!

### Describe the bug

Several users (mostly using non-chromium browsers and a mobile internet connection) have problems to join a Galene conference (they are visible in the sidebar but can't establish video/audio). While investigating into the issue (started a thread over at [galene's repo ](https://github.com/jech/galene/issues/86)) I found out **that my TURN server seems to be configured incorrectly:** `/relay-test` in Galene fails: `Relay test failed: Error: timeout`

I checked if the server is running and read the configuration, but I can't find out what the problem is. So if you have a tip, I'd be very happy about it

### Context

- Hardware: VPS (4 core, 8GB RAM) at Hetzner.com
- YunoHost version: 4.1.8
- I have access to my server: through ssh mainly, web console in emergency cases
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no – basic user, didn't touch system files or similar
- installed package in question: 0.3.4~ynh1

### Steps to reproduce

- using `/relay-test` in Galene (on my server obviously)

### Expected behavior

TURN server should be up and running. `/relay-test` should succeed.

### Logs | What else I have done

_I replaced the ip with ip.add.of.server and the url with myurl.org – hope that is ok. Of course I can privately share the IP if you want to perform a test or so._

[Here](https://paste.yunohost.org/qecuwayora.sql) are the logs of the coturn-galene service.
I did some other things to understand what the problem is, but didn't really understand the implications.

- checked if the coturn service is running in yunohost admin area and restarted it
- did the `/relay-test` in Galene on several machines/networks – always fails
- checked the port with `nc -v myurl.org 1194` – suceeds
- checked the turn server with [this code for chrome/firefox console (the one under the line)](https://stackoverflow.com/a/34033938): the answer was "no"
- checked the turn server [with this tool](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/): see screens
![ICE transport value: relay](https://user-images.githubusercontent.com/46564824/116861148-f11c2e00-ac02-11eb-9375-9a647d52640f.png)
![ICE transport value: all](https://user-images.githubusercontent.com/46564824/116861154-f24d5b00-ac02-11eb-8fa0-d77615c5845d.png)

**Comment by lapineige** [comment]
Thanks a lot for the super detailed and structured description of your issue :)


I suppose restarting both Galène and the TURN server did not work ?
Could you share your Galène ICE config file, just in case ?

Do you have any other TURN server running ? (for instance the one from Matrix-Synapse app)

**Comment by jakobkilian** [comment]
Very welcome, it is me to say thx for the development of galene for ynh!

Right, restart didn't change the situation. Just found out that galene has this failure in its logs:
`May 03 14:26:39 galene[876]: 2021/05/03 14:26:39 client: websocket: close 1006 (abnormal closure): unexpected EOF
` 
Don't know it it is important...

My `./opt/yunohost/galene/data/ice-servers.json `  is:
```
[
    {
        "urls": [
            "turn:myurl.org:1194",
            "turn:myurl.org:1194?transport=tcp"
        ],
        "username": "galene",
        "credential": "XXXX"
    }
]
```

Two thoughts:
- Never saw the passwort XXXX (deleted the original) – is it a hash? Because it is definitely not my admin password
- I use the [ynh redirect app](https://github.com/YunoHost-Apps/redirect_ynh/blob/master/README.md) to direct subdomains like `XY.myurl.org` to `myurl.org/group/XY` – if this is somehow interesting of the investigation.

**Comment by lapineige** [comment]
> unexpected EOF

That means that the is an error in the End Of a File. Often an error with wrongly formatted json or such…
Maybe that ICE config file has a bad syntax ?

**Comment by jakobkilian** [comment]
Hmmm, actually it really is the content i posted... Can't see any bad syntax in that file...

**Comment by jech** [comment]
@lapineige, no, in this case, the "unexpected EOF" means that a client disconnected without sending the close handshake.  This may happen for example if a browser crashes, and is nothing to worry about.

The issue is somewhere else.

**Comment by jakobkilian** [comment]
Ok I tried to get myself deeper into how the turn server should work on my server. When I tried to make the turnserver listen to the default ports I got the message:

```
admin@XXX:/opt/yunohost/galene$ ./galene -http :8443
2021/05/10 10:23:53 Server: listen tcp :8443: bind: address already in use
admin@XXX:/opt/yunohost/galene$ ./galene -turn :1194
2021/05/10 10:24:06 Starting built-in TURN server on :1194
2021/05/10 10:24:06 Server: listen tcp :8443: bind: address already in use
```

Is this normal? 8443 is already inn use because of galene itself... 

`tcp6       0      0 :::8443                 :::*                    LISTEN      29553/galene        
`

Furthermore, even with coturn-galene turned off there seems to be another turnsever running. Where is this coming from (can't imagine another app using turn and din't configure it myself) and can this conflict with the coturn-galene?  

```
tcp        0      0 myIP4ADDR:3478          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 myIP4ADDR:3478          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 myIP4ADDR:3478          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 myIP4ADDR:3478          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3478          0.0.0.0:*               LISTEN      951/turnserver            
tcp        0      0 myIP4ADDR:3479          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3479          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 myIP4ADDR:3479          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3479          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 myIP4ADDR:3479          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3479          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 myIP4ADDR:3479          0.0.0.0:*               LISTEN      951/turnserver      
tcp        0      0 127.0.0.1:3479          0.0.0.0:*               LISTEN      951/turnserver   
tcp6       0      0 ::1:3478                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3478          :::*                    LISTEN      951/turnserver      
tcp6       0      0 ::1:3478                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3478          :::*                    LISTEN      951/turnserver      
tcp6       0      0 ::1:3478                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3478          :::*                    LISTEN      951/turnserver      
tcp6       0      0 ::1:3478                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3478          :::*                    LISTEN      951/turnserver      
tcp6       0      0 ::1:3479                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3479          :::*                    LISTEN      951/turnserver      
tcp6       0      0 ::1:3479                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3479          :::*                    LISTEN      951/turnserver      
tcp6       0      0 ::1:3479                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3479          :::*                    LISTEN      951/turnserver      
tcp6       0      0 ::1:3479                :::*                    LISTEN      951/turnserver      
tcp6       0      0 myIP6ADDR:3479          :::*                    LISTEN      951/turnserver   
udp        0      0 myIP4ADDR:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 myIP4ADDR:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 myIP4ADDR:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 myIP4ADDR:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3478          0.0.0.0:*                           951/turnserver      
udp        0      0 myIP4ADDR:3479          0.0.0.0:*                           951/turnserver      
udp        0      0 myIP4ADDR:3479          0.0.0.0:*                           951/turnserver      
udp        0      0 myIP4ADDR:3479          0.0.0.0:*                           951/turnserver      
udp        0      0 myIP4ADDR:3479          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3479          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3479          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3479          0.0.0.0:*                           951/turnserver      
udp        0      0 127.0.0.1:3479          0.0.0.0:*                           951/turnserver      
udp6       0      0 ::1:3478                :::*                                951/turnserver      
udp6       0      0 ::1:3478                :::*                                951/turnserver      
udp6       0      0 ::1:3478                :::*                                951/turnserver      
udp6       0      0 ::1:3478                :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3478          :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3478          :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3478          :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3478          :::*                                951/turnserver      
udp6       0      0 ::1:3479                :::*                                951/turnserver      
udp6       0      0 ::1:3479                :::*                                951/turnserver      
udp6       0      0 ::1:3479                :::*                                951/turnserver      
udp6       0      0 ::1:3479                :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3479          :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3479          :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3479          :::*                                951/turnserver      
udp6       0      0 myIP6ADDR:3479          :::*                                951/turnserver      

```

When co-turn is started the server appears with `netstat -tulpn`  as "9500/turnserver " 
I also checked the Firewall and the ports (1194 and 8443) are open.

**What could I check next? Or is my knowledge just to low to proceed any further?** ;-)

And just to add: issue can also be reproduced by using a [guest network of a Fritz.Box](https://en.avm.de/service/fritzbox/fritzbox-7590/knowledge-base/publication/show/294_Setting-up-Wi-Fi-guest-access-in-the-FRITZ-Box/) (Maybe the higher ports are prohibited there too?

**Comment by ericgaspar** [comment]
@jakobkilian Sorry for the late reply.
You can test this other repo which uses Galène with its integrated TURN server. it doesn't work with ipv6 i believe.
`sudo yunohost app install https://github.com/YunoHost-Apps/galene_ynh/tree/without-turn`
Tell me if you are able to ping the TURN server with `/relay-test`

**Comment by jakobkilian** [comment]
Wow. It works out of the box! Thank you so much!
Also tried to set up an own server with instructions by my hoster, but naw, didn't work and I still don't really understand the whole topic -.- But for now, this works, thx!

**Comment by cairobraga** [comment]
@ericgaspar sorry to bring this back from the dead, but I tried installing the suggested alternative tree of the app but I get this:

`Error: Requirements are not met for galene, the package yunohost (0:) must be >= 4.2.4`

My Yunohost is 4.2.6, I don't understand what's happening. can you help me?

**Comment by ericgaspar** [comment]
Someone add the same error with a different app this week. I have no idea of the problem...
