### ISSUE TITLE
Error in the coturn script

### ISSUE THREAD

**Issue by stevenmache** [YunoHost-Apps/galene_ynh#44]
Hi, I receive this error since the last update. I though this was due to my ynh 4.2.0 but I updated to the last stable ynh 4.2.4 and I still receive this error. I am not sure what the problem is, look like an invalid parameter on a function call? 
(rpi4b ynh 4.2.4 galene 0.3.4~ynh1) 

> Cronic detected failure or error output for the command:
bash -c /opt/yunohost/galene/Coturn_config_rotate.sh;

RESULT CODE: 1

ERROR OUTPUT:
<html>
<head>
    <meta charset="utf-8">
    <style type="text/css">
        html, body, #partner, iframe {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        body {
            overflow: hidden;
        }
    </style>
    <meta content="NOW" name="expires">
    <meta content="index, follow, all" name="GOOGLEBOT">
    <meta content="index, follow, all" name="robots">
    
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;
            user-scalable=0;" name="viewport">
</head>
<body>

<div id="partner"></div>
<script type="text/javascript">
    function getParam() {
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == '\''domain'\'') {
                return pair[1];
            }
        }
        return  window.location.host;
    }
    ;

    document.write(
            '\''<script type="text/javascript" language="JavaScript"'\''
                    + '\''src="//sedoparking.com/frmpark/'\''
                    + getParam() + '\''/'\''
                    + '\''sedopark'\''
                    + '\''/park.js">'\''
                    + '\''<\/script>'\''
    );
</script>
</body>
</html>' ']'
<html>
<head>
    <meta charset="utf-8">
    <style type="text/css">
        html, body, #partner, iframe {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        body {
            overflow: hidden;
        }
    </style>
    <meta content="NOW" name="expires">
    <meta content="index, follow, all" name="GOOGLEBOT">
    <meta content="index, follow, all" name="robots">
    
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;
            user-scalable=0;" name="viewport">
</head>
<body>

<div id="partner"></div>
<script type="text/javascript">
    function getParam() {
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == '\''domain'\'') {
                return pair[1];
            }
        }
        return  window.location.host;
    }
    ;

    document.write(
            '\''<script type="text/javascript" language="JavaScript"'\''
                    + '\''src="//sedoparking.com/frmpark/'\''
                    + getParam() + '\''/'\''
                    + '\''sedopark'\''
                    + '\''/park.js">'\''
                    + '\''<\/script>'\''
    );
</script>
</body>
</html>'
<html>
<head>
    <meta charset="utf-8">
    <style type="text/css">
        html, body, #partner, iframe {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        body {
            overflow: hidden;
        }
    </style>
    <meta content="NOW" name="expires">
    <meta content="index, follow, all" name="GOOGLEBOT">
    <meta content="index, follow, all" name="robots">
    
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;
            user-scalable=0;" name="viewport">
</head>
<body>

<div id="partner"></div>
<script type="text/javascript">
    function getParam() {
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == '\''domain'\'') {
                return pair[1];
            }
        }
        return  window.location.host;
    }
    ;

    document.write(
            '\''<script type="text/javascript" language="JavaScript"'\''
                    + '\''src="//sedoparking.com/frmpark/'\''
                    + getParam() + '\''/'\''
                    + '\''sedopark'\''
                    + '\''/park.js">'\''
                    + '\''<\/script>'\''
    );
</script>
</body>
</html>'
Invalid argument: --

STANDARD OUTPUT:

TRACE-ERROR OUTPUT:
+ ynh_validate_ip --family=4 --ip_address=109.8.95.73
+ local legacy_args=fi
+ args_array=([f]=family= [i]=ip_address=)
+ local -A args_array
+ local family
+ local ip_address
+ ynh_handle_getopts_args --family=4 --ip_address=109.8.95.73
+ set +o xtrace
+ '[' 4 == 4 ']'
+ python /dev/stdin
+ external_IP_line=external-ip=109.8.95.73/__IPV6__
+ '[' -n '<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style type="text/css">
        html, body, #partner, iframe {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        body {
            overflow: hidden;
        }
    </style>
    <meta content="NOW" name="expires">
    <meta content="index, follow, all" name="GOOGLEBOT">
    <meta content="index, follow, all" name="robots">
    
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;
            user-scalable=0;" name="viewport">
</head>
<body>

<div id="partner"></div>
<script type="text/javascript">
    function getParam() {
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == '\''domain'\'') {
                return pair[1];
            }
        }
        return  window.location.host;
    }
    ;

    document.write(
            '\''<script type="text/javascript" language="JavaScript"'\''
                    + '\''src="//sedoparking.com/frmpark/'\''
                    + getParam() + '\''/'\''
                    + '\''sedopark'\''
                    + '\''/park.js">'\''
                    + '\''<\/script>'\''
    );
</script>
</body>
</html>' ']'
+ ynh_validate_ip6 '--ip_address=<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style type="text/css">
        html, body, #partner, iframe {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        body {
            overflow: hidden;
        }
    </style>
    <meta content="NOW" name="expires">
    <meta content="index, follow, all" name="GOOGLEBOT">
    <meta content="index, follow, all" name="robots">
    
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;
            user-scalable=0;" name="viewport">
</head>
<body>

<div id="partner"></div>
<script type="text/javascript">
    function getParam() {
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == '\''domain'\'') {
                return pair[1];
            }
        }
        return  window.location.host;
    }
    ;

    document.write(
            '\''<script type="text/javascript" language="JavaScript"'\''
                    + '\''src="//sedoparking.com/frmpark/'\''
                    + getParam() + '\''/'\''
                    + '\''sedopark'\''
                    + '\''/park.js">'\''
                    + '\''<\/script>'\''
    );
</script>
</body>
</html>'
+ local legacy_args=i
+ args_array=([i]=ip_address=)
+ local -A args_array
+ local ip_address
+ ynh_handle_getopts_args '--ip_address=<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style type="text/css">
        html, body, #partner, iframe {
            height: 100%;
            width: 100%;
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        body {
            overflow: hidden;
        }
    </style>
    <meta content="NOW" name="expires">
    <meta content="index, follow, all" name="GOOGLEBOT">
    <meta content="index, follow, all" name="robots">
    
    <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0;
            user-scalable=0;" name="viewport">
</head>
<body>

<div id="partner"></div>
<script type="text/javascript">
    function getParam() {
        var query = window.location.search.substring(1);
        var vars = query.split("&");
        for (var i = 0; i < vars.length; i++) {
            var pair = vars[i].split("=");
            if (pair[0] == '\''domain'\'') {
                return pair[1];
            }
        }
        return  window.location.host;
    }
    ;

    document.write(
            '\''<script type="text/javascript" language="JavaScript"'\''
                    + '\''src="//sedoparking.com/frmpark/'\''
                    + getParam() + '\''/'\''
                    + '\''sedopark'\''
                    + '\''/park.js">'\''
                    + '\''<\/script>'\''
    );
</script>
</body>
</html>'
+ set +o xtrace
+ ynh_validate_ip --family=6 '--ip_address=<!DOCTYPE' 'html>' '<html>' '<head>' '<meta' 'charset="utf-8">' '<style' 'type="text/css">' html, body, '#partner,' iframe '{' height: '100%;' width: '100%;' margin: '0;' padding: '0;' border: '0;' outline: '0;' font-size: '100%;' vertical-align: 'baseline;' background: 'transparent;' '}' body '{' overflow: 'hidden;' '}' '</style>' '<meta' 'content="NOW"' 'name="expires">' '<meta' 'content="index,' follow, 'all"' 'name="GOOGLEBOT">' '<meta' 'content="index,' follow, 'all"' 'name="robots">' '' '<meta' 'content="width=device-width;' 'initial-scale=1.0;' 'maximum-scale=1.0;' 'user-scalable=0;"' 'name="viewport">' '</head>' '<body>' '<div' 'id="partner"></div>' '<script' 'type="text/javascript">' function 'getParam()' '{' var query = 'window.location.search.substring(1);' var vars = 'query.split("&");' for '(var' i = '0;' i '<' 'vars.length;' 'i++)' '{' var pair = 'vars[i].split("=");' if '(pair[0]' == ''\''domain'\'')' '{' return 'pair[1];' '}' '}' return 'window.location.host;' '}' ';' 'document.write(' ''\''<script' 'type="text/javascript"' 'language="JavaScript"'\''' + ''\''src="//sedoparking.com/frmpark/'\''' + 'getParam()' + ''\''/'\''' + ''\''sedopark'\''' + ''\''/park.js">'\''' + ''\''<\/script>'\''' ');' '</script>' '</body>' '</html>'
+ local legacy_args=fi
+ args_array=([f]=family= [i]=ip_address=)
+ local -A args_array
+ local family
+ local ip_address
+ ynh_handle_getopts_args --family=6 '--ip_address=<!DOCTYPE' 'html>' '<html>' '<head>' '<meta' 'charset="utf-8">' '<style' 'type="text/css">' html, body, '#partner,' iframe '{' height: '100%;' width: '100%;' margin: '0;' padding: '0;' border: '0;' outline: '0;' font-size: '100%;' vertical-align: 'baseline;' background: 'transparent;' '}' body '{' overflow: 'hidden;' '}' '</style>' '<meta' 'content="NOW"' 'name="expires">' '<meta' 'content="index,' follow, 'all"' 'name="GOOGLEBOT">' '<meta' 'content="index,' follow, 'all"' 'name="robots">' '' '<meta' 'content="width=device-width;' 'initial-scale=1.0;' 'maximum-scale=1.0;' 'user-scalable=0;"' 'name="viewport">' '</head>' '<body>' '<div' 'id="partner"></div>' '<script' 'type="text/javascript">' function 'getParam()' '{' var query = 'window.location.search.substring(1);' var vars = 'query.split("&");' for '(var' i = '0;' i '<' 'vars.length;' 'i++)' '{' var pair = 'vars[i].split("=");' if '(pair[0]' == ''\''domain'\'')' '{' return 'pair[1];' '}' '}' return 'window.location.host;' '}' ';' 'document.write(' ''\''<script' 'type="text/javascript"' 'language="JavaScript"'\''' + ''\''src="//sedoparking.com/frmpark/'\''' + 'getParam()' + ''\''/'\''' + ''\''sedopark'\''' + ''\''/park.js">'\''' + ''\''<\/script>'\''' ');' '</script>' '</body>' '</html>'
+ set +o xtrace
+ ret_code=1
+ echo 'Invalid argument: --'
Invalid argument: --
+ exit 1

**Comment by ericgaspar** [comment]
I suggest you uninstall galene and reinstall the version from this branch:
`sudo yunohost app install https://github.com/YunoHost-Apps/galene_ynh/tree/without-turn`.
This version of galène does not install coturn as it is integrated into Galène. The only limitation is that IPV6 addresses are not supported.
My plan is to have this version in master and for those who want IPV6 for coturn, there is the coturn_ynh package available ...

**Comment by stevenmache** [comment]
Ok I'll do that. I do not have ipv6 anyway !
thanks eric

**Comment by stevenmache** [comment]
Just a question since I never install in cli. I'll be asked the info by the install script (subdomain where where to install galene..) thanks

**Comment by ericgaspar** [comment]
You will get the same question as in the webadmin. and don't' forget to open ports in you box... Galène is using `1194` for turn.

**Comment by stevenmache** [comment]
Done,  thanks.

Small point: it seems the uninstall script does not remove the cron job:
>Cronic detected failure or error output for the command:
bash -c /opt/yunohost/galene/Coturn_config_rotate.sh;
RESULT CODE: 127
ERROR OUTPUT:
bash: /opt/yunohost/galene/Coturn_config_rotate.sh: No such file or directory

**Comment by ericgaspar** [comment]
@stevenmache The cron job to trigger `Coturn_config_rotate.sh` is optional and added manually by the user. The remove script does not remove it by default... maybe it should check if a script was added and remove it if so...

**Comment by ericgaspar** [comment]
This should fix the issue : https://github.com/YunoHost-Apps/galene_ynh/commit/a32248a7cac2ea234ec6b4ce2cd4b74686302753

**Comment by stevenmache** [comment]
👍
