### ISSUE TITLE
Traduction Française ?

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/galene_ynh#46]
Hello, exited to try this must have software on my yunohost.
To make galène more friendly user for no English user, is there a way to translate the (simple) interface in French ?
It seems necessary to install on a dedicated domain, true ? As I don't see folder name proposition on install procedure.

**Comment by tituspijean** [comment]
> Hello, exited to try this must have software on my yunohost.
To make galène more friendly user for no English user, is there a way to translate the (simple) interface in French ?

cf. issue 33 over at https://github.com/jech/galene/issues 😉 
Every piece of language is in the `static` folder, you have to edit all the HTML files. It is not quite scalable, but we could imagine to apply a patch, or overwrite the files after installation. You can head over to the upstream repo to contribute though. 😃 

> It seems necessary to install on a dedicated domain, true ? As I don't see folder name proposition on install procedure.

Correct, if you are not asked for a path, then you need a whole domain. 😉

**Comment by lapineige** [comment]
I wonder if we can configure it (I mean this yunohost package) to use a folder instead of a full domain 🤔

**Comment by ericgaspar** [comment]
I guess that the French translation should/will be handled upstream : https://github.com/jech/galene/pull/56
