### ISSUE TITLE
. Question concerning access to statistics:

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/galene_ynh#49]
> . Question concerning access to statistics:
> I tried all the username and password saved on Yunohost and during installation and it doesn't work.
> In the documentation of Galène, I saw that it was enough to define a couple "user: password" in the file "/opt/yunohost/galene/data/passwd" then to restart the service galene, but that does not not working !
> 

_Originally posted by @rican13 in https://github.com/YunoHost-Apps/galene_ynh/issues/42#issuecomment-830269549_

I'm wondering if galene_ynh users are having this problem and if there are any who successfully login to access the statistics page at `domain.ltd/stats` 

I also cannot access it...

**Comment by lapineige** [comment]
I can't access it, I am prompted for login+password, it doesn't work (with my Yunohost credentials).

**Comment by rican13** [comment]
Hello,
I managed to access the stats, by applying the following commands.
Cordially.

Bonjour,
J'ai réussi à accéder aux stats, en appliquant les manips suivantes.
Cordialement.

# Dans mon installation, Galène est installé dans le dossier suivant :
sudo ls -al /opt/yunohost/galene/

# Supprimer le fichier passwd
sudo rm /opt/yunohost/galene/data/passwd

# Définir un "<userid>" et "<password>"
sudo echo "<userid>:<password>" > /opt/yunohost/galene/data/passwd

# Remettre les droits nécessaires
sudo chown -Rf galene:galene /opt/yunohost/galene/data
sudo chmod -Rf go-rw /opt/yunohost/galene/data
sudo ls -al /opt/yunohost/galene/data

# Relancer le service Galène
sudo systemctl restart galene && systemctl status galene

# Accèder aux stats
https://<site-web>/stats

**Comment by ericgaspar** [comment]
Thank you both for sharing!
@tituspijean found the bug on psswd file #52 . \o/
