### ISSUE TITLE
Upgrade from 3.5 t 4 error

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/galene_ynh#59]
When trying upgrade, I have this message
`Integrating service in YunoHost...

usage: yunohost service add name

[-h] [-d DESCRIPTION] [-l LOG [LOG ...]]

[-t {file,systemd} [{file,systemd} ...]]

[--test_status TEST_STATUS]

[--test_conf TEST_CONF]

[--needs_exposed_ports PORT [PORT ...]] [-n]

[-s STATUS]

yunohost service add: error: argument --needs_exposed_ports: invalid int value: ''

[Error] Upgrade failed.

The user turnserver was not found

13872 I: Creating /var/lib/turn/turndb from /usr/share/doc/coturn/schema.sql

The app was restored to the way it was before the failed upgrade.`

**Comment by ericgaspar** [comment]
As this is a big package upgrade you have to remove the 0.3.5 before... -> https://forum.yunohost.org/t/galene-videoconferencing-server/14730/13

**Comment by tutle** [comment]
Thanks, solved
