### ISSUE TITLE
Only two groups can be used in Yunohost Galene

### ISSUE THREAD

**Issue by ralphshinevar** [YunoHost-Apps/galene_ynh#63]
### Describe the bug

When I create groups in Yunohost Galene, only two groups actually work.  I created five groups with .json files, placed them in the appropriate folder, but only two show on the web site and only two actually work.  The other groups, when put them in the url, give an internal server error.  
### Context

- Hardware: Old laptop or computer; Lenovo Think Server (TS140)
- YunoHost version: 4.2.8.3
- I have access to my server:  Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- Created .json file for group.  SCP group to the groups directory.  

### Expected behavior

All groups should appear on the web site.  I should be able to log in to any person from any group once the group is selected.  
In all of the .json files the line for public is:  "public": true,

### Logs

No logs

![galene-two-groups](https://user-images.githubusercontent.com/56281781/134269590-f4607687-fe6e-48f7-a68f-1eee7e710147.jpg)
If applicable and useful, add screenshots to help explain your problem.

**Comment by ericgaspar** [comment]
I have tested to add new groups and I cannot reproduce your issue.
Did you restart Galène service after adding new groups?

**Comment by ralphshinevar** [comment]
Duh!  My error!  Poor sysadmin performance.  Checked the Galene logs and there was some syntax error in those three .json files I created.  One too many commas!  Fixed the files, restarted Galene and all is working.
