### ISSUE TITLE
Groupe name with spaces are not supported

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/galene_ynh#9]
I tried to install the app, and to choose a custom group name that included spaces.
It fails:

>DEBUG + mv -f /opt/yunohost/galene/groups/groupname.json /opt/yunohost/galene/groups/Groupe par défaut.json
WARNING mv: target 'défaut.json' is not a directory

I don't know if it's an issue with the app or the install script. In the first case, we should warn or (better, but I don't know if it's doable) prevent them from using a group name with spaces.

**Comment by ericgaspar** [comment]
The way *Galène* creates groups is to name a JSON file with the name of the group…. : `public` -> `public.json` which of course make thinks tricky.

Two possibilities
- Creat a default group like `public` and explain in the README how to set up other groups.
- Explain the naming limitations in the manifest so that the user can automatically define the first group. (and of course we still have to explain how to create other groups in the README file.)

**Comment by lapineige** [comment]
> The way Galène creates groups is to name a JSON file with the name of the group…. : public -> public.json which of course make thinks tricky.

I understood that later on… Thanks for documenting it anyway.

Especially because there is no admin interface yet (and because it require CLI to make/modify groups), I do think it's better to let users define their first group directly during installation.
I think we should let them define 4 things:
1. administrator login+password
2. (first) group name
2. is it a public group (listed in home page listed)
3. is it possible to connect : anonymously (without any pseudo+password) / only with a password (but no pseudo required) / using login + password.

But for 3), it's not easy to let them provide multiple [user+password] credentials. So maybe that's more an advanced feature that they would manually add. Being able to connect anonymously or with a password (and possibly a pseudo) is good enough in my opinion.

Maybe we could also provide a template file as an example ?

I'm ok to work on improving the readme if you wish :)

**Comment by jech** [comment]
It's a problem with the script — upstream Galène has no problem with spaces in group names.  You just need to make sure you apply the proper quoting to the filename in the script.

**Comment by ericgaspar** [comment]
@jech Many thanks for pointing this out! That should be corrected with #21

**Comment by ericgaspar** [comment]
#22 should fix the issue
