### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/galene_ynh#98]
### Describe the bug

Upgrade from 0.6.1-ynh1  to 0.6.1-ynh3  failed

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.0.9.15
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

   1. Upgrade Galene via webadmin
   2. Result: Upgrade failed

### Expected behavior

Upgrade succeeds

### Logs

Maybe this is the important part

```
Upgrading dependencies...
Upgrading NGINX web server configuration...
Building app...
Updating a configuration file...
touch: cannot touch '/opt/yunohost/galene/live_ldap/data/galene-ldap.json': No such file or directory
[Error] Upgrade failed.
The app was restored to the way it was before the failed upgrade.
Could not upgrade galene: An error occurred inside the app upgrade script
```

https://paste.yunohost.org/raw/jeruyomeze

**Comment by ericgaspar** [comment]
Closing with #99

**Comment by Ddataa** [comment]
service galene-ldap has the wrong path
`galene_ldap.service: Failed to locate executable /opt/yunohost/galene/live_ldap/galene-ldap: No such file or directory`

the file is at path `/opt/yunohost/galene/live_ldap/data/galene-ldap.json`

**Comment by ericgaspar** [comment]
Since #87, we have normalized the path  `/opt/yunohost/galene` to `/var/www/galene`.
I guess that wasn't an issue so far but with LDAP support addad you may need to remove the app and reinstall it.

**Comment by Ddataa** [comment]
understood

having a link to changelog when upgrading an app would be **awesome**

**Comment by ericgaspar** [comment]
Well, actually we added a version comparison script in order to force reinstalling the app... How did you get pass it I don't know.

https://github.com/YunoHost-Apps/galene_ynh/blob/212f44396d85a441a25aa934cb86401a6489a517/scripts/upgrade#L33-L36
